version: "3.9"

services:
  mysql:
    image: mysql:8.3
    container_name: user_following_service_mysql
    restart: unless-stopped
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_USER_FOLLOWING_SERVICE_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_USER_FOLLOWING_SERVICE_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: .
    container_name: user_following_service_api
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      - mysql
    ports:
      - "${APP_PORT}:8080"

volumes:
  mysql_data:
